before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w -X main.version={{.Version}}
  main: ./cmd/discord-slowmode-bot/main.go
archives:
- format: zip
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-next"
changelog:
  sort: asc
